style_edition = "2024"
group_imports = "StdExternalCrate"
imports_granularity = "Module"
format_code_in_doc_comments = true
use_field_init_shorthand = true
max_width = 100
hard_tabs = false
use_small_heuristics = "Max"
newline_style = "Unix"
match_block_trailing_comma = true
wrap_comments = true
comment_width = 100
normalize_comments = true
normalize_doc_attributes = true
reorder_impl_items = true
