name: CI

on:
  push:
    branches:
      - master
    paths:
      - '**/Cargo.toml'
  pull_request:
    paths:
      - '**/Cargo.toml'

permissions:
  contents: read
  actions: read

jobs:
  cargo-audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-audit-${{ hashFiles('**/Cargo.toml') }}

      - run: |
          cargo install cargo-audit
          cargo audit --deny=warnings
