name: DOC

on:
  push:
    branches:
      - master
    tags:
      - "*"
  pull_request:

env:
  CARGO_TERM_COLOR: always

permissions:
  contents: read
  actions: read

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    env:
      BRANCH_NAME: ${{ github.event_name == 'pull_request' && github.head_ref || (github.ref_name == '' && 'master' || github.ref_name) }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false
      - uses: dtolnay/rust-toolchain@4305c38b25d97ef35a8ad1f985ccf2d2242004f2 # stable
      - run: |
          .github/doc/doc.py ${BRANCH_NAME}
          ls -l ./target/docs
      - uses: peaceiris/actions-gh-pages@4f9cc6602d3f66b9c108549d475ec49e8ef4d45e # v4.0.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./target/docs
          publish_branch: gh-pages
        if: github.ref_type == 'tag' || github.ref == 'refs/heads/master'
