name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'New version (e.g. 0.4.0)'
        required: true
        type: string
    branches:
      - master

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v4
        with:
          ref: master

      - name: Set version
        id: set_version
        run: |
          echo "VERSION=${{ github.event.inputs.version }}" >> $GITHUB_ENV

      - name: Update version in Cargo.toml
        run: |
          sed -i "s/^version = \".*\"/version = \"${VERSION}\"/" Cargo.toml

      - name: Commit and tag version bump
        run: |
          git config user.name "Andrei Avram"
          git config user.email "6795248+andreiavrammsd@users.noreply.github.com"
          git commit -am "Release v${VERSION}"
          git tag "v${VERSION}"

      - name: Push changes
        run: |
          git push origin master
          git push origin "v${VERSION}"

      - name: Create GitHub release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ env.VERSION }}
          name: v${{ env.VERSION }}
          generate_release_notes: false
